export default {
  introduction: 'Introduction',
  concepts: 'Concepts',
  identifier: 'Identifier',
  item: 'Dependency item',
  binding: 'Binding',
  'declare-dependency': 'Declare Dependency',
  react: 'Use in React',
  rx: 'Use with RxJS',
  hierarchy: 'Hierarchy Injection System',
  forwardref: 'forwardRef',
  'with-new': '@WithNew Decorator',
  env: 'Setup Dev Environment',
  faq: 'FAQ',
};
