export default {
  'introduction': 'Introduction',
  'concepts': 'Concepts',
  'identifier': 'Identifier',
  'item': 'Dependency item',
  'hook': 'Hooks',
  'binding': 'Binding',
  'relationship': 'Dependency Relationship',
  'injector': 'Injector',
  'with-new': 'With New Decorator',
  'hierarchy': 'Hierarchy Injection System',
  'forwardref': 'forwardRef',
  'react': 'Using in React',
  'env': 'Setup Dev Environment',
  'debug': 'Debug',
}
