[install]
linker = "hoisted"

[test]
preload = [ "./happydom.ts" ]
coverageSkipTestFiles = true
coverageReporter = [
  "text",
  "lcov"
]
coverageDir = "coverage"
coveragePathIgnorePatterns = [
  "happydom.ts",
  "src/__testing__/**",
]
coverageThreshold = { line = 1.0, function = 1.0 }
